#!/usr/bin/env python

import sys

def factorize(n):
    factors = []
    i = 2
    while i*i <= n:
        if n % i == 0:
            factors.append(i)
            n //= i
        else:
            i += 1
    if n > 1:
        factors.append(n)
    return factors

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)

    filename = sys.argv[1]
    try:
        with open(filename) as f:
            for line in f:
                n = int(line.strip())
                factors = factorize(n)
                print("{}={}".format(n, "*".join(str(f) for f in factors)))
    except IOError:
        print("File not found: {}".format(filename))
        sys.exit(1)
