#!/usr/bin/env python

import sys

def factorize(n):
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return i, n//i
    return None, None

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <file>")
        sys.exit(1)

    filename = sys.argv[1]
    try:
        with open(filename) as f:
            for line in f:
                n = int(line.strip())
                p, q = factorize(n)
                print(f"{n}={p}*{q}")
    except FileNotFoundError:
        print(f"File not found: {filename}")
        sys.exit(1)
